* Решения
** terms prepaid old WPF
Использует проект приложения из папки "terms prepaid" и WpfControlLibrary. Хотя эта версия была в последний раз закомитченна в 2017-03-31. Я думал что она является устаревшей и не содержит журнала заявок, но только в ней был баг с падением путёвок, значит это боевая версия.
** terms prepaid new WPF
Использует проект приложения из папки "terms prepaid-new" и WpfControlLibrary-new. Последний коммит от 2017-03-15.
* Пaпки
** RequestJournal
Первая версия журнала заявок. Видимо так и не пошла в использование и была заменена в библиотеке WpfControlLibrary.
** terms prepaid-leftover
Эта ветка была создана мной, n.kudryavtsev исходя из теории о том, что проекты внутри проектов корневой и являются рабочими. На самом деле наоборот. Туда поверх был залит код из какой-то непошедшей в продакшн версии с машины разработчиков. Является абсолютно устаревшей. Со временем удалить.
** terms-prepaid-chaos и terms-prepaid-new-chaos
В этих версиях главного проекта помимо самого проекта лежит ещё и устаревшая версия всего решения целиком. Сохранены при расчистке. Со временем следует удалить.
