//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdr
    {
        public System.DateTime calldate { get; set; }
        public string clid { get; set; }
        public string src { get; set; }
        public string dst { get; set; }
        public string dcontext { get; set; }
        public string channel { get; set; }
        public string dstchannel { get; set; }
        public string lastapp { get; set; }
        public string lastdata { get; set; }
        public int duration { get; set; }
        public int billsec { get; set; }
        public string disposition { get; set; }
        public int amaflags { get; set; }
        public string accountcode { get; set; }
        public string uniqueid { get; set; }
        public string userfield { get; set; }
        public string did { get; set; }
        public string recordingfile { get; set; }
        public float call_charge { get; set; }
        public string from_did { get; set; }
    }
}
