//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_CallRecordStatus
    {
        public mk_CallRecordStatus()
        {
            this.mk_CallRecords = new HashSet<mk_CallRecord>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<mk_CallRecord> mk_CallRecords { get; set; }
    }
}
