//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatus2
    {
        public RequestStatus2()
        {
            this.Request = new HashSet<Request2>();
            this.RequestStatusHistory = new HashSet<RequestStatusHistory2>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<Request2> Request { get; set; }
        public virtual ICollection<RequestStatusHistory2> RequestStatusHistory { get; set; }
    }
}
