//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestMessage2
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int RequestId { get; set; }
        public System.DateTime Date { get; set; }
        public string SenderAddress { get; set; }
        public string DestinationAddress { get; set; }
        public bool Seen { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public string Theme { get; set; }
        public bool IsIncomming { get; set; }
        public int InReplyToId { get; set; }
        public bool Reply { get; set; }
    
        public virtual Request2 Request { get; set; }
        public virtual RequestMessageAttachment2 RequestMessageAttachment { get; set; }
    }
}
