//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RequestsJournalContainer : DbContext
    {
        public RequestsJournalContainer()
            : base("name=RequestsJournalContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RequestMessage2> RequestMessage2Set { get; set; }
        public DbSet<Request2> Request2Set { get; set; }
        public DbSet<RequestType2> RequestType2Set { get; set; }
        public DbSet<RequestStatus2> RequestStatus2Set { get; set; }
        public DbSet<RequestStatusHistory2> RequestStatusHistory2Set { get; set; }
        public DbSet<RequestMessageAttachment2> RequestMessageAttachment2Set { get; set; }
    }
}
