//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request2
    {
        public Request2()
        {
            this.RequestMessage = new HashSet<RequestMessage2>();
            this.RequestStatusHistory = new HashSet<RequestStatusHistory2>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int RequestTypeId { get; set; }
        public int RequestStatusId { get; set; }
        public Nullable<int> US_KEY { get; set; }
    
        public virtual ICollection<RequestMessage2> RequestMessage { get; set; }
        public virtual RequestType2 RequestType { get; set; }
        public virtual RequestStatus2 RequestStatus { get; set; }
        public virtual ICollection<RequestStatusHistory2> RequestStatusHistory { get; set; }
    }
}
