//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatusHistory2
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int RequestStatusId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual RequestStatus2 RequestStatus { get; set; }
        public virtual Request2 Request { get; set; }
    }
}
