#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="lanta")]
	public partial class TouristDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTuristService(TuristService instance);
    partial void UpdateTuristService(TuristService instance);
    partial void DeleteTuristService(TuristService instance);
    partial void InsertTurist(Turist instance);
    partial void UpdateTurist(Turist instance);
    partial void DeleteTurist(Turist instance);
    #endregion
		
		public TouristDataDataContext() : 
				base(global::DataService.Properties.Settings.Default.lantaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TouristDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TouristDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TouristDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TouristDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TuristService> TuristServices
		{
			get
			{
				return this.GetTable<TuristService>();
			}
		}
		
		public System.Data.Linq.Table<Turist> Turists
		{
			get
			{
				return this.GetTable<Turist>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mk_hotels_by_dlKey", IsComposable=true)]
		public IQueryable<mk_hotels_by_dlKeyResult> mk_hotels_by_dlKey([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dlKey)
		{
			return this.CreateMethodCallQuery<mk_hotels_by_dlKeyResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dlKey);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuristService")]
	public partial class TuristService : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TU_TUKEY;
		
		private int _TU_DLKEY;
		
		private string _TU_NUMDOC;
		
		private System.Nullable<short> _TU_NUMROOM;
		
		private string _TU_SEAT;
		
		private System.Nullable<short> _TU_AREA;
		
		private System.Nullable<System.DateTime> _TU_DOCDATE;
		
		private System.Data.Linq.Binary _ROWID;
		
		private int _TU_IDKEY;
		
		private EntityRef<Turist> _Turist;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTU_TUKEYChanging(int value);
    partial void OnTU_TUKEYChanged();
    partial void OnTU_DLKEYChanging(int value);
    partial void OnTU_DLKEYChanged();
    partial void OnTU_NUMDOCChanging(string value);
    partial void OnTU_NUMDOCChanged();
    partial void OnTU_NUMROOMChanging(System.Nullable<short> value);
    partial void OnTU_NUMROOMChanged();
    partial void OnTU_SEATChanging(string value);
    partial void OnTU_SEATChanged();
    partial void OnTU_AREAChanging(System.Nullable<short> value);
    partial void OnTU_AREAChanged();
    partial void OnTU_DOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnTU_DOCDATEChanged();
    partial void OnROWIDChanging(System.Data.Linq.Binary value);
    partial void OnROWIDChanged();
    partial void OnTU_IDKEYChanging(int value);
    partial void OnTU_IDKEYChanged();
    #endregion
		
		public TuristService()
		{
			this._Turist = default(EntityRef<Turist>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_TUKEY", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int TU_TUKEY
		{
			get
			{
				return this._TU_TUKEY;
			}
			set
			{
				if ((this._TU_TUKEY != value))
				{
					if (this._Turist.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTU_TUKEYChanging(value);
					this.SendPropertyChanging();
					this._TU_TUKEY = value;
					this.SendPropertyChanged("TU_TUKEY");
					this.OnTU_TUKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_DLKEY", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int TU_DLKEY
		{
			get
			{
				return this._TU_DLKEY;
			}
			set
			{
				if ((this._TU_DLKEY != value))
				{
					this.OnTU_DLKEYChanging(value);
					this.SendPropertyChanging();
					this._TU_DLKEY = value;
					this.SendPropertyChanged("TU_DLKEY");
					this.OnTU_DLKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_NUMDOC", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string TU_NUMDOC
		{
			get
			{
				return this._TU_NUMDOC;
			}
			set
			{
				if ((this._TU_NUMDOC != value))
				{
					this.OnTU_NUMDOCChanging(value);
					this.SendPropertyChanging();
					this._TU_NUMDOC = value;
					this.SendPropertyChanged("TU_NUMDOC");
					this.OnTU_NUMDOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_NUMROOM", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> TU_NUMROOM
		{
			get
			{
				return this._TU_NUMROOM;
			}
			set
			{
				if ((this._TU_NUMROOM != value))
				{
					this.OnTU_NUMROOMChanging(value);
					this.SendPropertyChanging();
					this._TU_NUMROOM = value;
					this.SendPropertyChanged("TU_NUMROOM");
					this.OnTU_NUMROOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_SEAT", DbType="VarChar(4)", UpdateCheck=UpdateCheck.Never)]
		public string TU_SEAT
		{
			get
			{
				return this._TU_SEAT;
			}
			set
			{
				if ((this._TU_SEAT != value))
				{
					this.OnTU_SEATChanging(value);
					this.SendPropertyChanging();
					this._TU_SEAT = value;
					this.SendPropertyChanged("TU_SEAT");
					this.OnTU_SEATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_AREA", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> TU_AREA
		{
			get
			{
				return this._TU_AREA;
			}
			set
			{
				if ((this._TU_AREA != value))
				{
					this.OnTU_AREAChanging(value);
					this.SendPropertyChanging();
					this._TU_AREA = value;
					this.SendPropertyChanged("TU_AREA");
					this.OnTU_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_DOCDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> TU_DOCDATE
		{
			get
			{
				return this._TU_DOCDATE;
			}
			set
			{
				if ((this._TU_DOCDATE != value))
				{
					this.OnTU_DOCDATEChanging(value);
					this.SendPropertyChanging();
					this._TU_DOCDATE = value;
					this.SendPropertyChanged("TU_DOCDATE");
					this.OnTU_DOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWID", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ROWID
		{
			get
			{
				return this._ROWID;
			}
			set
			{
				if ((this._ROWID != value))
				{
					this.OnROWIDChanging(value);
					this.SendPropertyChanging();
					this._ROWID = value;
					this.SendPropertyChanged("ROWID");
					this.OnROWIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_IDKEY", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int TU_IDKEY
		{
			get
			{
				return this._TU_IDKEY;
			}
			set
			{
				if ((this._TU_IDKEY != value))
				{
					this.OnTU_IDKEYChanging(value);
					this.SendPropertyChanging();
					this._TU_IDKEY = value;
					this.SendPropertyChanged("TU_IDKEY");
					this.OnTU_IDKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Turist_TuristService", Storage="_Turist", ThisKey="TU_TUKEY", OtherKey="TU_KEY", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Turist Turist
		{
			get
			{
				return this._Turist.Entity;
			}
			set
			{
				Turist previousValue = this._Turist.Entity;
				if (((previousValue != value) 
							|| (this._Turist.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Turist.Entity = null;
						previousValue.TuristServices.Remove(this);
					}
					this._Turist.Entity = value;
					if ((value != null))
					{
						value.TuristServices.Add(this);
						this._TU_TUKEY = value.TU_KEY;
					}
					else
					{
						this._TU_TUKEY = default(int);
					}
					this.SendPropertyChanged("Turist");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Turist")]
	public partial class Turist : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TU_DGCOD;
		
		private int _TU_KEY;
		
		private System.Nullable<System.DateTime> _TU_TURDATE;
		
		private string _TU_NAMERUS;
		
		private string _TU_NAMELAT;
		
		private string _TU_SHORTNAME;
		
		private System.Nullable<short> _TU_SEX;
		
		private string _TU_FNAMERUS;
		
		private string _TU_FNAMELAT;
		
		private string _TU_SNAMERUS;
		
		private string _TU_SNAMELAT;
		
		private System.Nullable<System.DateTime> _TU_BIRTHDAY;
		
		private string _TU_BIRTHCOUNTRY;
		
		private string _TU_BIRTHCITY;
		
		private string _TU_CITIZEN;
		
		private string _TU_POSTINDEX;
		
		private string _TU_POSTCITY;
		
		private string _TU_POSTSTREET;
		
		private string _TU_POSTBILD;
		
		private string _TU_POSTFLAT;
		
		private string _TU_PHONE;
		
		private string _TU_PHONECODE;
		
		private string _TU_PASPORTTYPE;
		
		private string _TU_PASPORTNUM;
		
		private System.Nullable<System.DateTime> _TU_PASPORTDATE;
		
		private System.Nullable<System.DateTime> _TU_PASPORTDATEEND;
		
		private string _TU_PASPORTBYWHOM;
		
		private System.Nullable<short> _TU_PLACE;
		
		private System.Nullable<short> _TU_ISANKETA;
		
		private int _TU_CREATOR;
		
		private int _TU_OWNER;
		
		private string _TU_PASPRUSER;
		
		private string _TU_PASPRUNUM;
		
		private System.Nullable<System.DateTime> _TU_PASPRUDATE;
		
		private string _TU_PASPRUBYWHOM;
		
		private string _TU_INSURPOLIS;
		
		private System.Nullable<double> _TU_INSURSUM;
		
		private System.Nullable<double> _TU_DISCOUNT;
		
		private System.Nullable<double> _TU_TYPEDISCOUNT;
		
		private System.Nullable<int> _TU_ID;
		
		private System.Nullable<short> _TU_ISMAIN;
		
		private System.Data.Linq.Binary _ROWID;
		
		private System.Nullable<int> _TU_AgentID;
		
		private string _TL_ADVDESC;
		
		private string _TL_ATTDESC;
		
		private string _TL_DOPDESC;
		
		private string _TL_FULLDESC;
		
		private string _TL_SMALLDESC;
		
		private System.Nullable<int> _TU_DGKEY;
		
		private System.Nullable<short> _TU_RealSex;
		
		private string _TU_EMAIL;
		
		private EntitySet<TuristService> _TuristServices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTU_DGCODChanging(string value);
    partial void OnTU_DGCODChanged();
    partial void OnTU_KEYChanging(int value);
    partial void OnTU_KEYChanged();
    partial void OnTU_TURDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnTU_TURDATEChanged();
    partial void OnTU_NAMERUSChanging(string value);
    partial void OnTU_NAMERUSChanged();
    partial void OnTU_NAMELATChanging(string value);
    partial void OnTU_NAMELATChanged();
    partial void OnTU_SHORTNAMEChanging(string value);
    partial void OnTU_SHORTNAMEChanged();
    partial void OnTU_SEXChanging(System.Nullable<short> value);
    partial void OnTU_SEXChanged();
    partial void OnTU_FNAMERUSChanging(string value);
    partial void OnTU_FNAMERUSChanged();
    partial void OnTU_FNAMELATChanging(string value);
    partial void OnTU_FNAMELATChanged();
    partial void OnTU_SNAMERUSChanging(string value);
    partial void OnTU_SNAMERUSChanged();
    partial void OnTU_SNAMELATChanging(string value);
    partial void OnTU_SNAMELATChanged();
    partial void OnTU_BIRTHDAYChanging(System.Nullable<System.DateTime> value);
    partial void OnTU_BIRTHDAYChanged();
    partial void OnTU_BIRTHCOUNTRYChanging(string value);
    partial void OnTU_BIRTHCOUNTRYChanged();
    partial void OnTU_BIRTHCITYChanging(string value);
    partial void OnTU_BIRTHCITYChanged();
    partial void OnTU_CITIZENChanging(string value);
    partial void OnTU_CITIZENChanged();
    partial void OnTU_POSTINDEXChanging(string value);
    partial void OnTU_POSTINDEXChanged();
    partial void OnTU_POSTCITYChanging(string value);
    partial void OnTU_POSTCITYChanged();
    partial void OnTU_POSTSTREETChanging(string value);
    partial void OnTU_POSTSTREETChanged();
    partial void OnTU_POSTBILDChanging(string value);
    partial void OnTU_POSTBILDChanged();
    partial void OnTU_POSTFLATChanging(string value);
    partial void OnTU_POSTFLATChanged();
    partial void OnTU_PHONEChanging(string value);
    partial void OnTU_PHONEChanged();
    partial void OnTU_PHONECODEChanging(string value);
    partial void OnTU_PHONECODEChanged();
    partial void OnTU_PASPORTTYPEChanging(string value);
    partial void OnTU_PASPORTTYPEChanged();
    partial void OnTU_PASPORTNUMChanging(string value);
    partial void OnTU_PASPORTNUMChanged();
    partial void OnTU_PASPORTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnTU_PASPORTDATEChanged();
    partial void OnTU_PASPORTDATEENDChanging(System.Nullable<System.DateTime> value);
    partial void OnTU_PASPORTDATEENDChanged();
    partial void OnTU_PASPORTBYWHOMChanging(string value);
    partial void OnTU_PASPORTBYWHOMChanged();
    partial void OnTU_PLACEChanging(System.Nullable<short> value);
    partial void OnTU_PLACEChanged();
    partial void OnTU_ISANKETAChanging(System.Nullable<short> value);
    partial void OnTU_ISANKETAChanged();
    partial void OnTU_CREATORChanging(int value);
    partial void OnTU_CREATORChanged();
    partial void OnTU_OWNERChanging(int value);
    partial void OnTU_OWNERChanged();
    partial void OnTU_PASPRUSERChanging(string value);
    partial void OnTU_PASPRUSERChanged();
    partial void OnTU_PASPRUNUMChanging(string value);
    partial void OnTU_PASPRUNUMChanged();
    partial void OnTU_PASPRUDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnTU_PASPRUDATEChanged();
    partial void OnTU_PASPRUBYWHOMChanging(string value);
    partial void OnTU_PASPRUBYWHOMChanged();
    partial void OnTU_INSURPOLISChanging(string value);
    partial void OnTU_INSURPOLISChanged();
    partial void OnTU_INSURSUMChanging(System.Nullable<double> value);
    partial void OnTU_INSURSUMChanged();
    partial void OnTU_DISCOUNTChanging(System.Nullable<double> value);
    partial void OnTU_DISCOUNTChanged();
    partial void OnTU_TYPEDISCOUNTChanging(System.Nullable<double> value);
    partial void OnTU_TYPEDISCOUNTChanged();
    partial void OnTU_IDChanging(System.Nullable<int> value);
    partial void OnTU_IDChanged();
    partial void OnTU_ISMAINChanging(System.Nullable<short> value);
    partial void OnTU_ISMAINChanged();
    partial void OnROWIDChanging(System.Data.Linq.Binary value);
    partial void OnROWIDChanged();
    partial void OnTU_AgentIDChanging(System.Nullable<int> value);
    partial void OnTU_AgentIDChanged();
    partial void OnTL_ADVDESCChanging(string value);
    partial void OnTL_ADVDESCChanged();
    partial void OnTL_ATTDESCChanging(string value);
    partial void OnTL_ATTDESCChanged();
    partial void OnTL_DOPDESCChanging(string value);
    partial void OnTL_DOPDESCChanged();
    partial void OnTL_FULLDESCChanging(string value);
    partial void OnTL_FULLDESCChanged();
    partial void OnTL_SMALLDESCChanging(string value);
    partial void OnTL_SMALLDESCChanged();
    partial void OnTU_DGKEYChanging(System.Nullable<int> value);
    partial void OnTU_DGKEYChanged();
    partial void OnTU_RealSexChanging(System.Nullable<short> value);
    partial void OnTU_RealSexChanged();
    partial void OnTU_EMAILChanging(string value);
    partial void OnTU_EMAILChanged();
    #endregion
		
		public Turist()
		{
			this._TuristServices = new EntitySet<TuristService>(new Action<TuristService>(this.attach_TuristServices), new Action<TuristService>(this.detach_TuristServices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_DGCOD", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TU_DGCOD
		{
			get
			{
				return this._TU_DGCOD;
			}
			set
			{
				if ((this._TU_DGCOD != value))
				{
					this.OnTU_DGCODChanging(value);
					this.SendPropertyChanging();
					this._TU_DGCOD = value;
					this.SendPropertyChanged("TU_DGCOD");
					this.OnTU_DGCODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_KEY", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int TU_KEY
		{
			get
			{
				return this._TU_KEY;
			}
			set
			{
				if ((this._TU_KEY != value))
				{
					this.OnTU_KEYChanging(value);
					this.SendPropertyChanging();
					this._TU_KEY = value;
					this.SendPropertyChanged("TU_KEY");
					this.OnTU_KEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_TURDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> TU_TURDATE
		{
			get
			{
				return this._TU_TURDATE;
			}
			set
			{
				if ((this._TU_TURDATE != value))
				{
					this.OnTU_TURDATEChanging(value);
					this.SendPropertyChanging();
					this._TU_TURDATE = value;
					this.SendPropertyChanged("TU_TURDATE");
					this.OnTU_TURDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_NAMERUS", DbType="VarChar(35)", UpdateCheck=UpdateCheck.Never)]
		public string TU_NAMERUS
		{
			get
			{
				return this._TU_NAMERUS;
			}
			set
			{
				if ((this._TU_NAMERUS != value))
				{
					this.OnTU_NAMERUSChanging(value);
					this.SendPropertyChanging();
					this._TU_NAMERUS = value;
					this.SendPropertyChanged("TU_NAMERUS");
					this.OnTU_NAMERUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_NAMELAT", DbType="VarChar(35)", UpdateCheck=UpdateCheck.Never)]
		public string TU_NAMELAT
		{
			get
			{
				return this._TU_NAMELAT;
			}
			set
			{
				if ((this._TU_NAMELAT != value))
				{
					this.OnTU_NAMELATChanging(value);
					this.SendPropertyChanging();
					this._TU_NAMELAT = value;
					this.SendPropertyChanged("TU_NAMELAT");
					this.OnTU_NAMELATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_SHORTNAME", DbType="VarChar(4) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TU_SHORTNAME
		{
			get
			{
				return this._TU_SHORTNAME;
			}
			set
			{
				if ((this._TU_SHORTNAME != value))
				{
					this.OnTU_SHORTNAMEChanging(value);
					this.SendPropertyChanging();
					this._TU_SHORTNAME = value;
					this.SendPropertyChanged("TU_SHORTNAME");
					this.OnTU_SHORTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_SEX", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> TU_SEX
		{
			get
			{
				return this._TU_SEX;
			}
			set
			{
				if ((this._TU_SEX != value))
				{
					this.OnTU_SEXChanging(value);
					this.SendPropertyChanging();
					this._TU_SEX = value;
					this.SendPropertyChanged("TU_SEX");
					this.OnTU_SEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_FNAMERUS", DbType="VarChar(15) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TU_FNAMERUS
		{
			get
			{
				return this._TU_FNAMERUS;
			}
			set
			{
				if ((this._TU_FNAMERUS != value))
				{
					this.OnTU_FNAMERUSChanging(value);
					this.SendPropertyChanging();
					this._TU_FNAMERUS = value;
					this.SendPropertyChanged("TU_FNAMERUS");
					this.OnTU_FNAMERUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_FNAMELAT", DbType="VarChar(15) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TU_FNAMELAT
		{
			get
			{
				return this._TU_FNAMELAT;
			}
			set
			{
				if ((this._TU_FNAMELAT != value))
				{
					this.OnTU_FNAMELATChanging(value);
					this.SendPropertyChanging();
					this._TU_FNAMELAT = value;
					this.SendPropertyChanged("TU_FNAMELAT");
					this.OnTU_FNAMELATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_SNAMERUS", DbType="VarChar(15)", UpdateCheck=UpdateCheck.Never)]
		public string TU_SNAMERUS
		{
			get
			{
				return this._TU_SNAMERUS;
			}
			set
			{
				if ((this._TU_SNAMERUS != value))
				{
					this.OnTU_SNAMERUSChanging(value);
					this.SendPropertyChanging();
					this._TU_SNAMERUS = value;
					this.SendPropertyChanged("TU_SNAMERUS");
					this.OnTU_SNAMERUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_SNAMELAT", DbType="VarChar(15)", UpdateCheck=UpdateCheck.Never)]
		public string TU_SNAMELAT
		{
			get
			{
				return this._TU_SNAMELAT;
			}
			set
			{
				if ((this._TU_SNAMELAT != value))
				{
					this.OnTU_SNAMELATChanging(value);
					this.SendPropertyChanging();
					this._TU_SNAMELAT = value;
					this.SendPropertyChanged("TU_SNAMELAT");
					this.OnTU_SNAMELATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_BIRTHDAY", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> TU_BIRTHDAY
		{
			get
			{
				return this._TU_BIRTHDAY;
			}
			set
			{
				if ((this._TU_BIRTHDAY != value))
				{
					this.OnTU_BIRTHDAYChanging(value);
					this.SendPropertyChanging();
					this._TU_BIRTHDAY = value;
					this.SendPropertyChanged("TU_BIRTHDAY");
					this.OnTU_BIRTHDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_BIRTHCOUNTRY", DbType="VarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string TU_BIRTHCOUNTRY
		{
			get
			{
				return this._TU_BIRTHCOUNTRY;
			}
			set
			{
				if ((this._TU_BIRTHCOUNTRY != value))
				{
					this.OnTU_BIRTHCOUNTRYChanging(value);
					this.SendPropertyChanging();
					this._TU_BIRTHCOUNTRY = value;
					this.SendPropertyChanged("TU_BIRTHCOUNTRY");
					this.OnTU_BIRTHCOUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_BIRTHCITY", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string TU_BIRTHCITY
		{
			get
			{
				return this._TU_BIRTHCITY;
			}
			set
			{
				if ((this._TU_BIRTHCITY != value))
				{
					this.OnTU_BIRTHCITYChanging(value);
					this.SendPropertyChanging();
					this._TU_BIRTHCITY = value;
					this.SendPropertyChanged("TU_BIRTHCITY");
					this.OnTU_BIRTHCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_CITIZEN", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string TU_CITIZEN
		{
			get
			{
				return this._TU_CITIZEN;
			}
			set
			{
				if ((this._TU_CITIZEN != value))
				{
					this.OnTU_CITIZENChanging(value);
					this.SendPropertyChanging();
					this._TU_CITIZEN = value;
					this.SendPropertyChanged("TU_CITIZEN");
					this.OnTU_CITIZENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_POSTINDEX", DbType="VarChar(8)", UpdateCheck=UpdateCheck.Never)]
		public string TU_POSTINDEX
		{
			get
			{
				return this._TU_POSTINDEX;
			}
			set
			{
				if ((this._TU_POSTINDEX != value))
				{
					this.OnTU_POSTINDEXChanging(value);
					this.SendPropertyChanging();
					this._TU_POSTINDEX = value;
					this.SendPropertyChanged("TU_POSTINDEX");
					this.OnTU_POSTINDEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_POSTCITY", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string TU_POSTCITY
		{
			get
			{
				return this._TU_POSTCITY;
			}
			set
			{
				if ((this._TU_POSTCITY != value))
				{
					this.OnTU_POSTCITYChanging(value);
					this.SendPropertyChanging();
					this._TU_POSTCITY = value;
					this.SendPropertyChanged("TU_POSTCITY");
					this.OnTU_POSTCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_POSTSTREET", DbType="VarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string TU_POSTSTREET
		{
			get
			{
				return this._TU_POSTSTREET;
			}
			set
			{
				if ((this._TU_POSTSTREET != value))
				{
					this.OnTU_POSTSTREETChanging(value);
					this.SendPropertyChanging();
					this._TU_POSTSTREET = value;
					this.SendPropertyChanged("TU_POSTSTREET");
					this.OnTU_POSTSTREETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_POSTBILD", DbType="VarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string TU_POSTBILD
		{
			get
			{
				return this._TU_POSTBILD;
			}
			set
			{
				if ((this._TU_POSTBILD != value))
				{
					this.OnTU_POSTBILDChanging(value);
					this.SendPropertyChanging();
					this._TU_POSTBILD = value;
					this.SendPropertyChanged("TU_POSTBILD");
					this.OnTU_POSTBILDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_POSTFLAT", DbType="VarChar(4)", UpdateCheck=UpdateCheck.Never)]
		public string TU_POSTFLAT
		{
			get
			{
				return this._TU_POSTFLAT;
			}
			set
			{
				if ((this._TU_POSTFLAT != value))
				{
					this.OnTU_POSTFLATChanging(value);
					this.SendPropertyChanging();
					this._TU_POSTFLAT = value;
					this.SendPropertyChanged("TU_POSTFLAT");
					this.OnTU_POSTFLATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PHONE", DbType="VarChar(60)", UpdateCheck=UpdateCheck.Never)]
		public string TU_PHONE
		{
			get
			{
				return this._TU_PHONE;
			}
			set
			{
				if ((this._TU_PHONE != value))
				{
					this.OnTU_PHONEChanging(value);
					this.SendPropertyChanging();
					this._TU_PHONE = value;
					this.SendPropertyChanged("TU_PHONE");
					this.OnTU_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PHONECODE", DbType="VarChar(5)", UpdateCheck=UpdateCheck.Never)]
		public string TU_PHONECODE
		{
			get
			{
				return this._TU_PHONECODE;
			}
			set
			{
				if ((this._TU_PHONECODE != value))
				{
					this.OnTU_PHONECODEChanging(value);
					this.SendPropertyChanging();
					this._TU_PHONECODE = value;
					this.SendPropertyChanged("TU_PHONECODE");
					this.OnTU_PHONECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PASPORTTYPE", DbType="VarChar(5)", UpdateCheck=UpdateCheck.Never)]
		public string TU_PASPORTTYPE
		{
			get
			{
				return this._TU_PASPORTTYPE;
			}
			set
			{
				if ((this._TU_PASPORTTYPE != value))
				{
					this.OnTU_PASPORTTYPEChanging(value);
					this.SendPropertyChanging();
					this._TU_PASPORTTYPE = value;
					this.SendPropertyChanged("TU_PASPORTTYPE");
					this.OnTU_PASPORTTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PASPORTNUM", DbType="VarChar(13)", UpdateCheck=UpdateCheck.Never)]
		public string TU_PASPORTNUM
		{
			get
			{
				return this._TU_PASPORTNUM;
			}
			set
			{
				if ((this._TU_PASPORTNUM != value))
				{
					this.OnTU_PASPORTNUMChanging(value);
					this.SendPropertyChanging();
					this._TU_PASPORTNUM = value;
					this.SendPropertyChanged("TU_PASPORTNUM");
					this.OnTU_PASPORTNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PASPORTDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> TU_PASPORTDATE
		{
			get
			{
				return this._TU_PASPORTDATE;
			}
			set
			{
				if ((this._TU_PASPORTDATE != value))
				{
					this.OnTU_PASPORTDATEChanging(value);
					this.SendPropertyChanging();
					this._TU_PASPORTDATE = value;
					this.SendPropertyChanged("TU_PASPORTDATE");
					this.OnTU_PASPORTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PASPORTDATEEND", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> TU_PASPORTDATEEND
		{
			get
			{
				return this._TU_PASPORTDATEEND;
			}
			set
			{
				if ((this._TU_PASPORTDATEEND != value))
				{
					this.OnTU_PASPORTDATEENDChanging(value);
					this.SendPropertyChanging();
					this._TU_PASPORTDATEEND = value;
					this.SendPropertyChanged("TU_PASPORTDATEEND");
					this.OnTU_PASPORTDATEENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PASPORTBYWHOM", DbType="VarChar(15)", UpdateCheck=UpdateCheck.Never)]
		public string TU_PASPORTBYWHOM
		{
			get
			{
				return this._TU_PASPORTBYWHOM;
			}
			set
			{
				if ((this._TU_PASPORTBYWHOM != value))
				{
					this.OnTU_PASPORTBYWHOMChanging(value);
					this.SendPropertyChanging();
					this._TU_PASPORTBYWHOM = value;
					this.SendPropertyChanged("TU_PASPORTBYWHOM");
					this.OnTU_PASPORTBYWHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PLACE", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> TU_PLACE
		{
			get
			{
				return this._TU_PLACE;
			}
			set
			{
				if ((this._TU_PLACE != value))
				{
					this.OnTU_PLACEChanging(value);
					this.SendPropertyChanging();
					this._TU_PLACE = value;
					this.SendPropertyChanged("TU_PLACE");
					this.OnTU_PLACEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_ISANKETA", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> TU_ISANKETA
		{
			get
			{
				return this._TU_ISANKETA;
			}
			set
			{
				if ((this._TU_ISANKETA != value))
				{
					this.OnTU_ISANKETAChanging(value);
					this.SendPropertyChanging();
					this._TU_ISANKETA = value;
					this.SendPropertyChanged("TU_ISANKETA");
					this.OnTU_ISANKETAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_CREATOR", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int TU_CREATOR
		{
			get
			{
				return this._TU_CREATOR;
			}
			set
			{
				if ((this._TU_CREATOR != value))
				{
					this.OnTU_CREATORChanging(value);
					this.SendPropertyChanging();
					this._TU_CREATOR = value;
					this.SendPropertyChanged("TU_CREATOR");
					this.OnTU_CREATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_OWNER", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int TU_OWNER
		{
			get
			{
				return this._TU_OWNER;
			}
			set
			{
				if ((this._TU_OWNER != value))
				{
					this.OnTU_OWNERChanging(value);
					this.SendPropertyChanging();
					this._TU_OWNER = value;
					this.SendPropertyChanged("TU_OWNER");
					this.OnTU_OWNERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PASPRUSER", DbType="VarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string TU_PASPRUSER
		{
			get
			{
				return this._TU_PASPRUSER;
			}
			set
			{
				if ((this._TU_PASPRUSER != value))
				{
					this.OnTU_PASPRUSERChanging(value);
					this.SendPropertyChanging();
					this._TU_PASPRUSER = value;
					this.SendPropertyChanged("TU_PASPRUSER");
					this.OnTU_PASPRUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PASPRUNUM", DbType="VarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string TU_PASPRUNUM
		{
			get
			{
				return this._TU_PASPRUNUM;
			}
			set
			{
				if ((this._TU_PASPRUNUM != value))
				{
					this.OnTU_PASPRUNUMChanging(value);
					this.SendPropertyChanging();
					this._TU_PASPRUNUM = value;
					this.SendPropertyChanged("TU_PASPRUNUM");
					this.OnTU_PASPRUNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PASPRUDATE", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> TU_PASPRUDATE
		{
			get
			{
				return this._TU_PASPRUDATE;
			}
			set
			{
				if ((this._TU_PASPRUDATE != value))
				{
					this.OnTU_PASPRUDATEChanging(value);
					this.SendPropertyChanging();
					this._TU_PASPRUDATE = value;
					this.SendPropertyChanged("TU_PASPRUDATE");
					this.OnTU_PASPRUDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_PASPRUBYWHOM", DbType="VarChar(45)", UpdateCheck=UpdateCheck.Never)]
		public string TU_PASPRUBYWHOM
		{
			get
			{
				return this._TU_PASPRUBYWHOM;
			}
			set
			{
				if ((this._TU_PASPRUBYWHOM != value))
				{
					this.OnTU_PASPRUBYWHOMChanging(value);
					this.SendPropertyChanging();
					this._TU_PASPRUBYWHOM = value;
					this.SendPropertyChanged("TU_PASPRUBYWHOM");
					this.OnTU_PASPRUBYWHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_INSURPOLIS", DbType="VarChar(15)", UpdateCheck=UpdateCheck.Never)]
		public string TU_INSURPOLIS
		{
			get
			{
				return this._TU_INSURPOLIS;
			}
			set
			{
				if ((this._TU_INSURPOLIS != value))
				{
					this.OnTU_INSURPOLISChanging(value);
					this.SendPropertyChanging();
					this._TU_INSURPOLIS = value;
					this.SendPropertyChanged("TU_INSURPOLIS");
					this.OnTU_INSURPOLISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_INSURSUM", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> TU_INSURSUM
		{
			get
			{
				return this._TU_INSURSUM;
			}
			set
			{
				if ((this._TU_INSURSUM != value))
				{
					this.OnTU_INSURSUMChanging(value);
					this.SendPropertyChanging();
					this._TU_INSURSUM = value;
					this.SendPropertyChanged("TU_INSURSUM");
					this.OnTU_INSURSUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_DISCOUNT", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> TU_DISCOUNT
		{
			get
			{
				return this._TU_DISCOUNT;
			}
			set
			{
				if ((this._TU_DISCOUNT != value))
				{
					this.OnTU_DISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._TU_DISCOUNT = value;
					this.SendPropertyChanged("TU_DISCOUNT");
					this.OnTU_DISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_TYPEDISCOUNT", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> TU_TYPEDISCOUNT
		{
			get
			{
				return this._TU_TYPEDISCOUNT;
			}
			set
			{
				if ((this._TU_TYPEDISCOUNT != value))
				{
					this.OnTU_TYPEDISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._TU_TYPEDISCOUNT = value;
					this.SendPropertyChanged("TU_TYPEDISCOUNT");
					this.OnTU_TYPEDISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_ID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> TU_ID
		{
			get
			{
				return this._TU_ID;
			}
			set
			{
				if ((this._TU_ID != value))
				{
					this.OnTU_IDChanging(value);
					this.SendPropertyChanging();
					this._TU_ID = value;
					this.SendPropertyChanged("TU_ID");
					this.OnTU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_ISMAIN", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> TU_ISMAIN
		{
			get
			{
				return this._TU_ISMAIN;
			}
			set
			{
				if ((this._TU_ISMAIN != value))
				{
					this.OnTU_ISMAINChanging(value);
					this.SendPropertyChanging();
					this._TU_ISMAIN = value;
					this.SendPropertyChanged("TU_ISMAIN");
					this.OnTU_ISMAINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWID", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ROWID
		{
			get
			{
				return this._ROWID;
			}
			set
			{
				if ((this._ROWID != value))
				{
					this.OnROWIDChanging(value);
					this.SendPropertyChanging();
					this._ROWID = value;
					this.SendPropertyChanged("ROWID");
					this.OnROWIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_AgentID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> TU_AgentID
		{
			get
			{
				return this._TU_AgentID;
			}
			set
			{
				if ((this._TU_AgentID != value))
				{
					this.OnTU_AgentIDChanging(value);
					this.SendPropertyChanging();
					this._TU_AgentID = value;
					this.SendPropertyChanged("TU_AgentID");
					this.OnTU_AgentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_ADVDESC", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TL_ADVDESC
		{
			get
			{
				return this._TL_ADVDESC;
			}
			set
			{
				if ((this._TL_ADVDESC != value))
				{
					this.OnTL_ADVDESCChanging(value);
					this.SendPropertyChanging();
					this._TL_ADVDESC = value;
					this.SendPropertyChanged("TL_ADVDESC");
					this.OnTL_ADVDESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_ATTDESC", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TL_ATTDESC
		{
			get
			{
				return this._TL_ATTDESC;
			}
			set
			{
				if ((this._TL_ATTDESC != value))
				{
					this.OnTL_ATTDESCChanging(value);
					this.SendPropertyChanging();
					this._TL_ATTDESC = value;
					this.SendPropertyChanged("TL_ATTDESC");
					this.OnTL_ATTDESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_DOPDESC", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TL_DOPDESC
		{
			get
			{
				return this._TL_DOPDESC;
			}
			set
			{
				if ((this._TL_DOPDESC != value))
				{
					this.OnTL_DOPDESCChanging(value);
					this.SendPropertyChanging();
					this._TL_DOPDESC = value;
					this.SendPropertyChanged("TL_DOPDESC");
					this.OnTL_DOPDESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_FULLDESC", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TL_FULLDESC
		{
			get
			{
				return this._TL_FULLDESC;
			}
			set
			{
				if ((this._TL_FULLDESC != value))
				{
					this.OnTL_FULLDESCChanging(value);
					this.SendPropertyChanging();
					this._TL_FULLDESC = value;
					this.SendPropertyChanged("TL_FULLDESC");
					this.OnTL_FULLDESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_SMALLDESC", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TL_SMALLDESC
		{
			get
			{
				return this._TL_SMALLDESC;
			}
			set
			{
				if ((this._TL_SMALLDESC != value))
				{
					this.OnTL_SMALLDESCChanging(value);
					this.SendPropertyChanging();
					this._TL_SMALLDESC = value;
					this.SendPropertyChanged("TL_SMALLDESC");
					this.OnTL_SMALLDESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_DGKEY", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> TU_DGKEY
		{
			get
			{
				return this._TU_DGKEY;
			}
			set
			{
				if ((this._TU_DGKEY != value))
				{
					this.OnTU_DGKEYChanging(value);
					this.SendPropertyChanging();
					this._TU_DGKEY = value;
					this.SendPropertyChanged("TU_DGKEY");
					this.OnTU_DGKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_RealSex", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> TU_RealSex
		{
			get
			{
				return this._TU_RealSex;
			}
			set
			{
				if ((this._TU_RealSex != value))
				{
					this.OnTU_RealSexChanging(value);
					this.SendPropertyChanging();
					this._TU_RealSex = value;
					this.SendPropertyChanged("TU_RealSex");
					this.OnTU_RealSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TU_EMAIL", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string TU_EMAIL
		{
			get
			{
				return this._TU_EMAIL;
			}
			set
			{
				if ((this._TU_EMAIL != value))
				{
					this.OnTU_EMAILChanging(value);
					this.SendPropertyChanging();
					this._TU_EMAIL = value;
					this.SendPropertyChanged("TU_EMAIL");
					this.OnTU_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Turist_TuristService", Storage="_TuristServices", ThisKey="TU_KEY", OtherKey="TU_TUKEY")]
		public EntitySet<TuristService> TuristServices
		{
			get
			{
				return this._TuristServices;
			}
			set
			{
				this._TuristServices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TuristServices(TuristService entity)
		{
			this.SendPropertyChanging();
			entity.Turist = this;
		}
		
		private void detach_TuristServices(TuristService entity)
		{
			this.SendPropertyChanging();
			entity.Turist = null;
		}
	}
	
	public partial class mk_hotels_by_dlKeyResult
	{
		
		private string _type_of;
		
		private string _country;
		
		private string _city;
		
		private string _name;
		
		private string _category;
		
		private string _namber;
		
		private string _TURDATE;
		
		private System.Nullable<int> _ndays;
		
		private System.Nullable<int> _night;
		
		private string _pansion;
		
		private string _stars;
		
		public mk_hotels_by_dlKeyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_of", DbType="VarChar(10)")]
		public string type_of
		{
			get
			{
				return this._type_of;
			}
			set
			{
				if ((this._type_of != value))
				{
					this._type_of = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(100)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this._country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="VarChar(100)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this._category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namber", DbType="VarChar(20)")]
		public string namber
		{
			get
			{
				return this._namber;
			}
			set
			{
				if ((this._namber != value))
				{
					this._namber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TURDATE", DbType="VarChar(10)")]
		public string TURDATE
		{
			get
			{
				return this._TURDATE;
			}
			set
			{
				if ((this._TURDATE != value))
				{
					this._TURDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ndays", DbType="Int")]
		public System.Nullable<int> ndays
		{
			get
			{
				return this._ndays;
			}
			set
			{
				if ((this._ndays != value))
				{
					this._ndays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_night", DbType="Int")]
		public System.Nullable<int> night
		{
			get
			{
				return this._night;
			}
			set
			{
				if ((this._night != value))
				{
					this._night = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pansion", DbType="VarChar(100)")]
		public string pansion
		{
			get
			{
				return this._pansion;
			}
			set
			{
				if ((this._pansion != value))
				{
					this._pansion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stars", DbType="VarChar(12)")]
		public string stars
		{
			get
			{
				return this._stars;
			}
			set
			{
				if ((this._stars != value))
				{
					this._stars = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
